#!/bin/bash

podman run \
	-d \
	--name prefect-server \
	-p 4200:4200 \
	-e PREFECT_SERVER_API_AUTH_STRING="$PREFECT_SERVER_API_AUTH_STRING" \
	prefecthq/prefect:3-latest \
	prefect server start --host 0.0.0.0
